### ISSUE TITLE
prescan: add number format

### ISSUE THREAD

**Issue by Zhykos** [Zhykos/autophoto#71]
For instance: `Found 12334 files.` should be `12.334` (I guess it's a point in English???)

Maybe the same improvement for the scanner

**Comment by AndreVale69** [comment]
@Zhykos Hi, I would like to work on this issue. I have already made a pull request to see what I have done. I added a simple method to format the number as you like. By default it is formatted in English (USA) format: `1000` becomes `1,000`. However, I added a simple enumeration that you can use to change the format. In addition, there is an url you can use if you want to add other values to the enumeration or if you need a different locale.

**Comment by Zhykos** [comment]
Hello @AndreVale69, welcome and thank you so much! 🙂 I'll check your PR 😉

**Comment by Zhykos** [comment]
Thank you again @AndreVale69 ! It's merged and will be released on the next 2.2.0 (see the dedicated PR)
